city=1
latitude=12.9715987
longitude=77.5945627
property_city=Bengaluru
property_name=Bengaluru
installation_city=Bengaluru
country=India
searched_address=Test yantra, Jayanagar, Bengaluru
map_url=https://maps.google.com/?q=Bengaluru,+Karnataka,+India&ftid=0x3bae1670c9b44e6d:0xf8dfc3e8517e4fe0
placeId=ChIJbU60yXAWrjsR4E9-UejD3_g
state=KA
preProdAppointment_venue=a16C1000000RKM1IAO
prodAppointment_venue=a090I00000ocyPWQAY
hfn_showroom = a09C2000002D55ZIAS

customer_address=Test yantra, South End Circle, Jaya Nagar 1st Block, Vijayarangam Layout, Jayanagar, Bengaluru, Karnataka, India
pincode=560061
project_name=test_project